import pytest
import yaml

WORKFLOW_PATH = ".github/workflows/trigger-qagent-analysis.yml"

@pytest.fixture(scope="module")
def workflow_content():
    with open(WORKFLOW_PATH, "r", encoding="utf-8") as f:
        content = yaml.safe_load(f)
    return content

def test_workflow_name_is_correct(workflow_content):
    assert workflow_content.get("name") == "Trigger QAgent"

def test_workflow_triggers_push_with_paths_ignore(workflow_content):
    on = workflow_content.get("on")
    assert on is not None, "'on' section must be present"
    push = on.get("push")
    assert push is not None, "'push' trigger must be present"
    branches = push.get("branches")
    assert branches is not None and isinstance(branches, list)
    assert "main" in branches or "master" in branches
    paths_ignore = push.get("paths-ignore")
    assert paths_ignore is not None and isinstance(paths_ignore, list)
    # Check that the paths-ignore patterns include the expected test file patterns
    expected_patterns = ['**/tests/**', '**/test_*', '**/*_test.*']
    for pattern in expected_patterns:
        assert pattern in paths_ignore

def test_workflow_triggers_workflow_dispatch(workflow_content):
    on = workflow_content.get("on")
    assert "workflow_dispatch" in on

def test_job_trigger_qagent_exists(workflow_content):
    jobs = workflow_content.get("jobs")
    assert jobs is not None and isinstance(jobs, dict)
    job = jobs.get("trigger-qagent")
    assert job is not None, "Job 'trigger-qagent' must be defined"
    runs_on = job.get("runs-on")
    assert runs_on == "ubuntu-latest"
    steps = job.get("steps")
    assert steps is not None and isinstance(steps, list)
    # Check that the curl command is present in the run step
    run_step = next((step for step in steps if "run" in step), None)
    assert run_step is not None, "There must be a step with a 'run' command"
    run_cmd = run_step["run"]
    assert "curl" in run_cmd
    assert "https://api.github.com/repos/jrcosta/qagent/dispatches" in run_cmd

def test_job_if_condition_prevents_loop(workflow_content):
    jobs = workflow_content.get("jobs")
    job = jobs.get("trigger-qagent")
    if_cond = job.get("if")
    assert if_cond is not None, "Job 'trigger-qagent' must have an 'if' condition"
    # Check that the condition contains the expected strings
    assert "[skip-qagent]" in if_cond
    assert "generated by QAgent" in if_cond
    # Check that the condition uses !contains and logical AND
    assert "!contains" in if_cond
    assert "&&" in if_cond

@pytest.mark.parametrize("commit_message,expected", [
    ("Fix bug in feature", True),
    ("[skip-qagent] temporary skip", False),
    ("This commit was generated by QAgent", False),
    ("generated by QAgent in message", False),
    ("Some other message", True),
])
def test_if_condition_commit_message_logic(commit_message, expected):
    """
    Simulate the if condition logic for commit messages:
    The job should run only if commit message does NOT contain '[skip-qagent]'
    AND does NOT contain 'generated by QAgent'.
    """
    contains_skip = "[skip-qagent]" in commit_message
    contains_generated = "generated by QAgent" in commit_message
    should_run = not contains_skip and not contains_generated
    assert should_run == expected