import pytest

def should_trigger_workflow(commit_message: str, changed_files: list[str]) -> bool:
    """
    Simula a lógica do workflow GitHub Actions para decidir se o job 'trigger-qagent' deve rodar.
    Baseado na condição 'if' do workflow e no filtro paths-ignore.

    Regras simuladas:
    - Se commit_message contém '[skip-qagent]', 'generated by QAgent' ou 'qagent/', não dispara.
    - Se todos os arquivos alterados são arquivos de teste (segundo os padrões paths-ignore), não dispara.
    - Caso contrário, dispara.
    """

    # Condição if do workflow
    if (
        '[skip-qagent]' in commit_message or
        'generated by QAgent' in commit_message or
        'qagent/' in commit_message
    ):
        return False

    # Padrões paths-ignore do workflow
    # Note: '**/tests/**' e '**/test/**' cobrem diretórios com 'test' ou 'tests'
    # '**/test_*' cobre arquivos começando com test_
    # '**/*_test.*' cobre arquivos terminando com _test.ext
    # '**/Test*.java', '**/*Test.java', '**/*Tests.java' cobrem arquivos Java de teste

    def is_test_file(path: str) -> bool:
        import fnmatch
        patterns = [
            '**/tests/**',
            '**/test/**',
            '**/test_*',
            '**/*_test.*',
            '**/Test*.java',
            '**/*Test.java',
            '**/*Tests.java',
        ]
        for pattern in patterns:
            if fnmatch.fnmatch(path, pattern):
                return True
        return False

    # Se todos os arquivos alterados são arquivos de teste, não dispara
    if changed_files and all(is_test_file(f) for f in changed_files):
        return False

    return True


@pytest.mark.parametrize("commit_message, changed_files, expected", [
    # 1. Commit que altera apenas arquivos de teste Java - não dispara
    ("Fix tests", ["src/com/example/TestExample.java", "src/com/example/OtherTest.java"], False),

    # 2. Commit que altera código e arquivos de teste Java - dispara
    ("Add feature and update tests", ["src/com/example/Feature.java", "src/com/example/TestExample.java"], True),

    # 3. Commit com mensagem contendo [skip-qagent] - não dispara
    ("Refactor code [skip-qagent]", ["src/com/example/Feature.java"], False),

    # 4. Commit com mensagem contendo 'qagent/' - não dispara
    ("Merge pull request #123 from jrcosta/qagent/tests-fix", ["src/com/example/Feature.java"], False),

    # 5. Commit normal sem nenhuma das condições acima - dispara
    ("Add new feature", ["src/com/example/Feature.java"], True),

    # Commit que altera apenas arquivos de teste em outros padrões - não dispara
    ("Update tests", ["tests/test_utils.py", "tests/test_main.py"], False),

    # Commit que altera código e arquivos de teste em outros padrões - dispara
    ("Fix bug and update tests", ["app/main.py", "tests/test_main.py"], True),

    # Commit com mensagem contendo 'generated by QAgent' - não dispara
    ("Auto commit generated by QAgent", ["src/com/example/Feature.java"], False),

    # Commit com arquivos não relacionados a teste - dispara
    ("Update README", ["README.md"], True),

    # Commit sem arquivos (edge case) - dispara (não há arquivos para ignorar)
    ("Empty commit", [], True),
])
def test_should_trigger_workflow(commit_message, changed_files, expected):
    assert should_trigger_workflow(commit_message, changed_files) is expected